version: "3.4"

services:
  unitystation:
    image: unitystation/prometheus-exporter
    restart: always

  prometheus:
    image: prom/prometheus
    volumes:
      - prometheus_data:/prometheus
      - /etc/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    restart: always

  grafana:
    image: grafana/grafana
    ports:
      - 3000:3000
    volumes:
      - grafana_data:/var/lib/grafana
    restart: always

volumes:
  prometheus_data:
  grafana_data: