global:
  scrape_interval: 5s
  evaluation_interval: 5s

rule_files:
  # - "first.rules"
  # - "second.rules"

scrape_configs:
  - job_name: "unitystation"
    static_configs:
      - targets: ["unitystation:7776"]