{
 "title": "Unitystation",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Server Population",
   "type": "graph",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short", "label": "Players" }
   ],
   "targets": [
    { "expr": "unitystation_players", "legendFormat": "{{server}}" }
   ]
  },
  {
   "title": "Restarts",
   "type": "graph",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 11 },
   "targets": [
    {
     "expr": "count(deriv(unitystation_players[10s]) < 0 and unitystation_players < 1)"
    }
   ]
  },
  {
   "title": "Playtime",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "h", "label": "Total Playtime" }
   ],
   "targets": [
    {
     "expr": "sum_over_time(unitystation_players[1d])*5/60/60",
     "legendFormat": "{{server}}"
    }
   ]
  },
  { "title": "Alerts", "type": "alertlist", "gridPos": { "h": 8, "w": 12, "x": 12, "y": 14 } }
 ]
}